export const MAP_API_KEY = 'AIzaSyAu2FKak-or23JMhOsnIB8wS-5zgJR2n64';
export const FS_CLIENT_ID = '4NECUCZ4WH4QZC4EVRZLJVLZQZH4QIP40TDXM3K5RBAQVU34';
export const FS_CLIENT_SECRET =
  'QHCONF5CBUGSEAIUGTFUWSLLVX4OBB2AYFSXWLRJW0FCNFPL';
